/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fft.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(03167663eece3efa6330cdb9efb1416b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <trt/fft.h>
// pydoc.h is automatically generated in the build directory
#include <fft_pydoc.h>

void bind_fft(py::module& m)
{

    using fft    = ::gr::trt::fft;


    py::class_<fft, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<fft>>(m, "fft", D(fft))

        .def(py::init(&fft::make),
           py::arg("fft_size"),
           py::arg("forward"),
           py::arg("shift") = false,
           py::arg("batch_size") = 1,
           py::arg("mem_model") = ::gr::trt::memory_model_t::TRADITIONAL,
           D(fft,make)
        )
        



        ;




}








