/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(passthrough.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3fd3a77af48a07ba6d261699eea4e11e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <trt/passthrough.h>
// pydoc.h is automatically generated in the build directory
#include <passthrough_pydoc.h>

void bind_passthrough(py::module& m)
{

    using passthrough    = ::gr::trt::passthrough;


    py::class_<passthrough, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<passthrough>>(m, "passthrough", D(passthrough))

        .def(py::init(&passthrough::make),
           py::arg("batch_size"),
           py::arg("mem_model"),
           D(passthrough,make)
        )
        



        ;




}








